apiVersion: v1
kind: Pod
metadata: 
  name: pod-config-secret
spec:
  containers:
    - name: container
      image: busybox
      command: ["sleep", "3600"]
      env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret
              key: Key
        - name: SSH_CONFIG
          valueFrom:
            configMapKeyRef:
              name: team-mission
              key: SSH